package gosrcfmt

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"

	"github.com/sirkon/message"
)

const (
	header = `/* This file was autogenerated via
-----------------------------------------
 %s
-----------------------------------------
do not touch it with bare hands!
*/

`
)

// Format formats data from src as a go code with gofmt utility
func Format(dest io.Writer, data []byte) {
	program := fmt.Sprintf(header, strings.Join(os.Args, " ")) + string(data)
	cmd := exec.Command("gofmt")
	cmd.Stdin = strings.NewReader(program)
	cmd.Stdout = dest
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		message.Criticalf("%s\n\n---------------------------------------\n%s", program, err)
	}
}

// FormatReader formats data from src as a go code with gofmt utility
func FormatReader(dest io.Writer, src io.Reader) {
	data, err := ioutil.ReadAll(src)
	if err != nil {
		panic(err)
	}
	Format(dest, data)
}
